apiVersion: v1
kind: Service
metadata:
  name: clusterip-service
spec:
  selector:
    app: web-server
  ports:
  - protocol: TCP
    port: 80 # The port the service exposes
    targetPort: 8080 # The port the container exposes
  type: ClusterIP