apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9100"  # Replace with the actual metrics port if different
    spec:
      containers:
      - name: web-server-container
        image: marwansabry/depi-web:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "500m"
            memory: "128Mi"
          requests:
            cpu: "250m"
            memory: "64Mi"